/**
 * @file NonCentralT.h
 * Defines a class representing non-central Student's t distributions with 
 * location and scale parameters.
 */
#ifndef DECBRL_NONCENTRALT_H
#define DECBRL_NONCENTRALT_H

#include <cassert>
#include <boost/math/distributions/students_t.hpp>
#include "util.h"

/**
 * Namespace all public functions and types defined in the DecBRL library.
 */
namespace dec_brl {

/**
 * Namespace for classes that represent probability distributions commonly
 * used in Bayesian Reinforcement Learning and Bayesian Analysis.
 * These classes are designed to work with distribution functions and classes
 * in the Boost.Math library.
 * @see http://www.boost.org
 */
namespace dist {

   /**
    * Class representing a scaled distribution of some type.
    * This class is defined using the
    * conventions and concepts of the boost math libraries.
    */
   template<class BaseDistribution, class RealType=double>
      class Scaled
   {
   public:

      /**
       * Type used to represent real values in this object.
       */
      typedef typename BaseDistribution::value_type value_type;

      /**
       * Boost.Math calculation policy used by this object.
       */
      typedef typename BaseDistribution::policy_type policy_type;

   private:

      /**
       * Location (the mode) of this distribution.
       */
      RealType loc_i;

      /**
       * The scale of this distribution.
       */
      RealType scale_i;

      /**
       * Underlying base distribution
       */
      BaseDistribution base_i;

   public: 

      /**
       * Constructs a new distribution with specified parameters.
       * @param base the base distribution to be scaled
       * @param loc location parameter for this distribution
       * @param scale scale parameter for this distribution
       */
      Scaled
      (
       const BaseDistribution& base,
       RealType loc=0,
       RealType scale=1
      )
      : loc_i(loc), scale_i(scale), base_i(base) {}

      /**
       * Returns a t distribution with the same degrees of freedom as
       * this distribution.
       */
      const BaseDistribution& base() const
      {
         return base_i;
      }

      /**
       * Returns the scale parameter for this distribution.
       */
      RealType scale() const { return scale_i; }

      /**
       * Returns the location parameter (mode) of this distribution.
       */
      RealType location() const { return loc_i; }

   }; // class Scaled

   /**
    * Class Representing non-central Student's t distribution with
    * location and scale parameters. This class is defined using the
    * conventions and concepts of the boost math libraries.
    */
   template<class RealType=double,class Policy=boost::math::policies::policy<> >
   class NonCentralT_Tmpl
   {
   private:

      /**
       * Convenience typedef for underlying T distribution type.
       */
      typedef boost::math::students_t_distribution<RealType, Policy> TDist;

      /**
       * Location (the mode) of this distribution.
       */
      RealType loc_i;

      /**
       * The scale of this distribution.
       */
      RealType scale_i;

      /**
       * Underlying t distribution
       */
      TDist tDist_i;

   public: 

      /**
       * Type of value required by the () operator for generating random
       * variates from this distribution. This is required to implement
       * the Random Distribution concept of the Boost Random library.
       */
      typedef RealType input_type;

      /**
       * Type used to represent real values in this object.
       */
      typedef RealType value_type;

      /**
       * Type used to represent real values in this object.
       * Used by Boost Random library.
       */
      typedef RealType result_type;

      /**
       * Boost.Math calculation policy used by this object.
       */
      typedef Policy policy_type;

      /**
       * Required to implement the Boost library Random Distribution concept.
       * Ensures independence between previous and subsequent random variates
       * generated by the () operator. However, only i.i.d. samples are
       * generated, this function does nothing.
       */
      void reset() {}

      /**
       * Generates a random variate from this distribution using a given
       * random number generator.
       */
      template<typename Engine> RealType operator()(Engine& engine)
      {
         // Implment using uniform01 and quantile function
         // also means we need to implment the quantile function
         return 0.0;

      } // operator()

      /**
       * Constructs a new distribution with specified parameters.
       * @param df degrees of freedom for this distribution
       * @param loc location parameter for this distribution
       * @param scale scale parameter for this distribution
       */
      NonCentralT_Tmpl
      (
       RealType df,
       RealType loc=0,
       RealType scale=1
      )
      : loc_i(loc), scale_i(scale), tDist_i(df) {}

      /**
       * Returns the degrees of freedom for this distribution.
       */
      RealType degrees_of_freedom() const
      {
         return tDist_i.degrees_of_freedom();
      }

      /**
       * Returns a t distribution with the same degrees of freedom as
       * this distribution.
       */
      const TDist& tDistribution() const
      {
         return tDist_i;
      }

      /**
       * Returns the scale parameter for this distribution.
       */
      RealType scale() const { return scale_i; }

      /**
       * Returns the location parameter (mode) of this distribution.
       */
      RealType location() const { return loc_i; }

   }; // class NonCentralT

   /**
    * Convenience typedef for distributions that uses the
    * default template parameters.
    */
   typedef class NonCentralT_Tmpl<> NonCentralT;

   /**
    * Class used to generate non-central t distributed random variates.
    */
   template<class RealType=double,class Policy=boost::math::policies::policy<> >
   class NonCentralTRandom_Tmpl
   {
   public:

      /**
       * Creates a new random generator for the specified distribution.
       */
      NonCentralTRandom_Tmpl(const NonCentralT_Tmpl<RealType,Policy>& dist) {}
      
      /**
       * Returns a random variate distributed according to this
       * generator's distribution.
       */
      RealType operator()() const { return 0.0; }

   }; // class NonCentralTRandom_Tmpl

   /**
    * Convenience typedef for random generator that uses default
    * template parameters.
    */
   typedef class NonCentralTRandom_Tmpl<> NonCentralTRandom;

} // namespace dist
} // namespace dec_brl

/**
 * The standard namespace for the Boost collection of libraries.
 * Here, we extend the boost namespace so that certain functions
 * are overloaded to work with our data types.
 * @see http://www.boost.org/
 */
namespace boost
{

/**
 * The standard namespace for the Boost.Math library.
 * Here, we extend the boost namespace so that certain functions
 * are overloaded to work with our data types.
 * @see http://www.boost.org/
 */
namespace math
{
   /**
    * Overloads the Boost.Math library variance function for
    * dec_brl::dist::NonCentralT_Tmpl objects.
    * @pre degrees of freedom must be greater than 2.
    * @returns the variance of the non-central t distribution.
    */
   template <class RealType, class Policy> RealType variance
   (
    const dec_brl::dist::NonCentralT_Tmpl<RealType, Policy>& dist
   )
   {
      RealType df = dist.degrees_of_freedom();
      return dist.scale()*dist.scale()*df/(df-2);
   }

   /**
    * Overloads the Boost.Math library standard_deviation function for
    * dec_brl::dist::NonCentralT_Tmpl objects.
    * @returns the standard deviation of the non-central t distribution.
    */
   template <class RealType, class Policy> RealType standard_deviation
   (
    const dec_brl::dist::NonCentralT_Tmpl<RealType, Policy>& dist
   )
   {
      return std::sqrt(variance(dist));
   }

   /**
    * The cumulative distribution function for NonCentralT distributions.
    * Overloads the Boost.Math library equivalent for our own distribution type.
    */
   template <class RealType, class Policy> RealType cdf
   (
    const dec_brl::dist::NonCentralT_Tmpl<RealType, Policy>& dist,
    const RealType& x
   )
   {
      RealType unscaled_param = (x-dist.location()) / dist.scale();
      return cdf(dist.tDistribution(),unscaled_param);
   }

   /**
    * The cumulative distribution function for the complement of a NonCentralT
    * distribution.
    */
   template <class RealType, class Policy> RealType cdf
   (
    const complemented2_type
      <dec_brl::dist::NonCentralT_Tmpl<RealType, Policy>, RealType>& c
   )
   {
      RealType unscaled_param = (c.param-c.dist.location()) / c.dist.scale();
      complemented2_type<students_t_distribution<RealType,Policy>, RealType>
         unscaled_c(c.dist.tDistribution(),unscaled_param);
      return cdf(unscaled_c);
   }

   /**
    * The quantile (inverse-cdf) for the NonCentralT distribution.
    * @param dist the probability distribution
    * @param p the position of the quantile requested.
    * @pre p must be in range [0,1].
    */
   template <class RealType, class Policy> RealType quantile
   (
    const dec_brl::dist::NonCentralT_Tmpl<RealType, Policy>& dist,
    const RealType& p
   )
   {
      RealType tQuantile = quantile(dist.tDistribution());
      return dist.scale()*tQuantile+dist.location();
   }
   
   /**
    * The quantile (inverse-cdf) for the complement NonCentralT distribution.
    * @param dist the probability distribution
    * @param p the position of the quantile requested.
    * @pre p must be in range [0,1].
    */
   template <class RealType, class Policy> RealType quantile
   (
    const complemented2_type
      <dec_brl::dist::NonCentralT_Tmpl<RealType, Policy>, RealType>& c
   )
   {
      complemented2_type<students_t_distribution<RealType,Policy>, RealType>
         unscaled_c(c.dist.tDistribution(),c.param);
      RealType tQuantile = quantile(unscaled_c);
      return c.dist.scale()*tQuantile+c.dist.location();
   }

} // namespace math
} // namespace boost


#endif // DECBRL_NONCENTRALT_H
